# Generated by Django 4.0.1 on 2022-02-04 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_foto_alter_contato_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 1, 13, 7, 966998, tzinfo=utc)),
        ),
    ]
